import type { Campaign, Scenario, Terrain, Unit } from './types'

export const positionKey = (row: number, col: number) => `${row}:${col}`

const terrainEntries: Array<[number, number, Terrain]> = [
  [0, 0, 'hill'],
  [0, 2, 'forest'],
  [0, 6, 'village'],
  [1, 1, 'forest'],
  [1, 5, 'forest'],
  [2, 0, 'river'],
  [2, 1, 'river'],
  [2, 2, 'river'],
  [2, 3, 'river'],
  [2, 4, 'river'],
  [2, 5, 'river'],
  [2, 6, 'river'],
  [3, 1, 'forest'],
  [3, 5, 'hill'],
  [4, 0, 'hill'],
  [4, 4, 'forest'],
  [5, 2, 'forest'],
  [5, 6, 'village'],
  [6, 0, 'hill'],
  [6, 5, 'forest'],
]

const terrain = Object.fromEntries(
  terrainEntries.map(([row, col, value]) => [positionKey(row, col), value]),
) as Record<string, Terrain>

const unit = (
  value: Omit<Unit, 'moved' | 'acted' | 'maxHp'> & { maxHp?: number },
): Unit => ({
  ...value,
  maxHp: value.maxHp ?? value.hp,
  moved: false,
  acted: false,
})

export const kalingaScenario: Scenario = {
  id: 'kalinga-261-bce',
  title: 'The Cost of Kalinga',
  subtitle: 'A tactical reconstruction of the Mauryan conquest, c. 261 BCE',
  rows: 8,
  cols: 7,
  maxTurns: 8,
  objective: 'Secure the Kalinga command standard before the eighth turn.',
  restraintTarget: 20,
  terrain,
  units: [
    unit({
      id: 'm-commander',
      faction: 'maurya',
      kind: 'commander',
      name: 'Mauryan Senapati',
      hp: 8,
      attack: 3,
      armor: 2,
      move: 2,
      range: 1,
      position: { row: 7, col: 3 },
    }),
    unit({
      id: 'm-elephant',
      faction: 'maurya',
      kind: 'elephant',
      name: 'Royal Elephant Corps',
      hp: 9,
      attack: 5,
      armor: 2,
      move: 2,
      range: 1,
      position: { row: 6, col: 2 },
    }),
    unit({
      id: 'm-archer',
      faction: 'maurya',
      kind: 'archer',
      name: 'Mauryan Bow Guard',
      hp: 5,
      attack: 3,
      armor: 0,
      move: 2,
      range: 3,
      position: { row: 7, col: 1 },
    }),
    unit({
      id: 'm-infantry',
      faction: 'maurya',
      kind: 'infantry',
      name: 'Mauryan Infantry',
      hp: 7,
      attack: 3,
      armor: 1,
      move: 3,
      range: 1,
      position: { row: 6, col: 4 },
    }),
    unit({
      id: 'm-cavalry',
      faction: 'maurya',
      kind: 'cavalry',
      name: 'Mauryan Cavalry',
      hp: 6,
      attack: 4,
      armor: 1,
      move: 4,
      range: 1,
      position: { row: 7, col: 5 },
    }),
    unit({
      id: 'k-commander',
      faction: 'kalinga',
      kind: 'commander',
      name: 'Kalinga War Council',
      hp: 8,
      attack: 3,
      armor: 2,
      move: 2,
      range: 1,
      position: { row: 0, col: 3 },
    }),
    unit({
      id: 'k-archer',
      faction: 'kalinga',
      kind: 'archer',
      name: 'Kalinga Archers',
      hp: 5,
      attack: 3,
      armor: 0,
      move: 2,
      range: 3,
      position: { row: 1, col: 1 },
    }),
    unit({
      id: 'k-infantry',
      faction: 'kalinga',
      kind: 'infantry',
      name: 'Kalinga Infantry',
      hp: 7,
      attack: 3,
      armor: 1,
      move: 3,
      range: 1,
      position: { row: 1, col: 4 },
    }),
    unit({
      id: 'k-spears',
      faction: 'kalinga',
      kind: 'infantry',
      name: 'Kalinga Spear Guard',
      hp: 7,
      attack: 4,
      armor: 1,
      move: 2,
      range: 1,
      position: { row: 1, col: 6 },
    }),
    unit({
      id: 'k-militia',
      faction: 'kalinga',
      kind: 'militia',
      name: 'Kalinga Citizen Militia',
      hp: 5,
      attack: 2,
      armor: 0,
      move: 3,
      range: 1,
      position: { row: 0, col: 5 },
    }),
  ],
  historyMoments: [
    {
      title: 'An independent Kalinga',
      kind: 'recorded-evidence',
      text:
        'Kalinga was outside Mauryan control before the conquest. Its exact political organization and the identity of its wartime leaders are not securely known.',
    },
    {
      title: 'Ashoka records the human toll',
      kind: 'claim-in-source',
      text:
        "Major Rock Edict XIII says 150,000 people were deported, 100,000 were killed, and many more died. These are Ashoka's stated figures, not independently verified totals.",
    },
    {
      title: 'The battlefield is not preserved',
      kind: 'gameplay-reconstruction',
      text:
        'No surviving Kalingan account gives formations, commanders, troop numbers, or a turn-by-turn battle. This map and every tactical unit are clearly labeled gameplay reconstruction.',
    },
    {
      title: 'From conquest to remorse',
      kind: 'recorded-evidence',
      text:
        'The same edict expresses remorse for the suffering in Kalinga and presents conquest through dhamma as preferable to armed conquest.',
    },
  ],
}

export const campaigns: readonly Campaign[] = [
  {
    id: 'mauryan-rise',
    figure: 'Chandragupta Maurya and Kautilya',
    title: 'Mauryan Rise',
    era: 'c. 4th century BCE',
    region: 'Magadha and the northwest',
    status: 'playable',
    evidence: '3D strategic reconstruction',
    description:
      'Build a living province, debate statecraft, recruit a fourfold army, and resolve a reconstructed frontier war across six seasons.',
  },
  {
    id: 'kalinga',
    figure: 'Ashoka Maurya',
    title: 'The Cost of Kalinga',
    era: 'c. 261 BCE',
    region: 'Kalinga',
    status: 'playable',
    evidence: 'Primary inscription + reconstruction',
    description:
      'Command a Mauryan field force, secure the objective, and confront the human cost recorded in Ashoka’s own edict.',
  },
  {
    id: 'vikramaditya',
    figure: 'Chandragupta II Vikramaditya',
    title: 'The Western Horizon',
    era: 'c. 4th-5th century CE',
    region: 'Malwa and Saurashtra',
    status: 'research',
    evidence: 'Coins and inscriptions; battle details lost',
    description:
      'A grand campaign against the Western Kshatrapas built around strong evidence for the conquest without inventing a falsely precise battle.',
  },
  {
    id: 'narrai',
    figure: 'Rani Durgavati',
    title: 'The Defiance at Narrai',
    era: '1564 CE',
    region: 'Gondwana',
    status: 'planned',
    evidence: 'Historical battle, multi-source campaign',
    description:
      'Use terrain, mobility, and resolve to defend Gondwana in a campaign centered on the Battle of Narrai.',
  },
  {
    id: 'saraighat',
    figure: 'Lachit Borphukan',
    title: 'The Brahmaputra Holds',
    era: '1671 CE',
    region: 'Assam',
    status: 'planned',
    evidence: 'Historical battle, river-warfare focus',
    description:
      'Coordinate boats, river forts, and land detachments during the Battle of Saraighat.',
  },
  {
    id: 'pratapgad',
    figure: 'Chhatrapati Shivaji Maharaj',
    title: 'The Hills of Pratapgad',
    era: '1659 CE',
    region: 'Western Ghats',
    status: 'planned',
    evidence: 'Historical battle, source comparison',
    description:
      'Plan movement through hill forts and broken terrain while the codex compares accounts of Pratapgad.',
  },
]
